<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class citiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('cities')->truncate();

        $cities = [
            ['postalcode' => '','name' => '基隆市', 'seq' => 1, 'used' => 1],
            ['postalcode' => '','name' => '台北市', 'seq' => 2, 'used' => 1],
            ['postalcode' => '','name' => '新北市', 'seq' => 3, 'used' => 1],
            ['postalcode' => '','name' => '桃園市', 'seq' => 4, 'used' => 1],
            ['postalcode' => '','name' => '新竹市', 'seq' => 5, 'used' => 1],
            ['postalcode' => '','name' => '新竹縣', 'seq' => 6, 'used' => 1],
            ['postalcode' => '','name' => '苗栗縣', 'seq' => 7, 'used' => 1],
            ['postalcode' => '','name' => '台中市', 'seq' => 8, 'used' => 1],
            ['postalcode' => '','name' => '彰化縣', 'seq' => 9, 'used' => 1],
            ['postalcode' => '','name' => '南投縣', 'seq' => 10, 'used' => 1],
            ['postalcode' => '','name' => '雲林縣', 'seq' => 11, 'used' => 1],
            ['postalcode' => '','name' => '嘉義市', 'seq' => 12, 'used' => 1],
            ['postalcode' => '','name' => '嘉義縣', 'seq' => 13, 'used' => 1],
            ['postalcode' => '','name' => '台南市', 'seq' => 14, 'used' => 1],
            ['postalcode' => '','name' => '高雄市', 'seq' => 15, 'used' => 1],
            ['postalcode' => '','name' => '屏東縣', 'seq' => 16, 'used' => 1],
            ['postalcode' => '','name' => '宜蘭縣', 'seq' => 17, 'used' => 1],
            ['postalcode' => '','name' => '花蓮縣', 'seq' => 18, 'used' => 1],
            ['postalcode' => '','name' => '台東縣', 'seq' => 19, 'used' => 1],
            ['postalcode' => '','name' => '澎湖縣', 'seq' => 20, 'used' => 1],
            ['postalcode' => '','name' => '金門縣', 'seq' => 21, 'used' => 1],
            ['postalcode' => '','name' => '連江縣', 'seq' => 22, 'used' => 1]
        ];

        DB::table('cities')->insert($cities);

        DB::table('cityareas')->truncate();

        $cityarea = [
            // 基隆市
            ['postalcode' => '200', 'city_id' => '1', 'name' => '仁愛區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '201', 'city_id' => '1', 'name' => '信義區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '202', 'city_id' => '1', 'name' => '中正區', 'seq' => 3, 'used' => 1],
            ['postalcode' => '203', 'city_id' => '1', 'name' => '中山區', 'seq' => 4, 'used' => 1],
            ['postalcode' => '204', 'city_id' => '1', 'name' => '安樂區', 'seq' => 5, 'used' => 1],
            ['postalcode' => '205', 'city_id' => '1', 'name' => '暖暖區', 'seq' => 6, 'used' => 1],
            ['postalcode' => '206', 'city_id' => '1', 'name' => '七堵區', 'seq' => 7, 'used' => 1],
            // 台北市
            ['postalcode' => '100', 'city_id' => '2', 'name' => '中正區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '103', 'city_id' => '2', 'name' => '大同區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '104', 'city_id' => '2', 'name' => '中山區', 'seq' => 3, 'used' => 1],
            ['postalcode' => '105', 'city_id' => '2', 'name' => '松山區', 'seq' => 4, 'used' => 1],
            ['postalcode' => '106', 'city_id' => '2', 'name' => '大安區', 'seq' => 5, 'used' => 1],
            ['postalcode' => '108', 'city_id' => '2', 'name' => '萬華區', 'seq' => 6, 'used' => 1],
            ['postalcode' => '110', 'city_id' => '2', 'name' => '信義區', 'seq' => 7, 'used' => 1],
            ['postalcode' => '111', 'city_id' => '2', 'name' => '士林區', 'seq' => 8, 'used' => 1],
            ['postalcode' => '112', 'city_id' => '2', 'name' => '北投區', 'seq' => 9, 'used' => 1],
            ['postalcode' => '114', 'city_id' => '2', 'name' => '內湖區', 'seq' => 10, 'used' => 1],
            ['postalcode' => '115', 'city_id' => '2', 'name' => '南港區', 'seq' => 11, 'used' => 1],
            ['postalcode' => '116', 'city_id' => '2', 'name' => '文山區', 'seq' => 12, 'used' => 1],
            // 新北市
            ['postalcode' => '207', 'city_id' => '3', 'name' => '萬里區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '208', 'city_id' => '3', 'name' => '金山區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '220', 'city_id' => '3', 'name' => '板橋區', 'seq' => 3, 'used' => 1],
            ['postalcode' => '221', 'city_id' => '3', 'name' => '汐止區', 'seq' => 4, 'used' => 1],
            ['postalcode' => '222', 'city_id' => '3', 'name' => '深坑區', 'seq' => 5, 'used' => 1],
            ['postalcode' => '223', 'city_id' => '3', 'name' => '石碇區', 'seq' => 6, 'used' => 1],
            ['postalcode' => '224', 'city_id' => '3', 'name' => '瑞芳區', 'seq' => 7, 'used' => 1],
            ['postalcode' => '226', 'city_id' => '3', 'name' => '平溪區', 'seq' => 8, 'used' => 1],
            ['postalcode' => '227', 'city_id' => '3', 'name' => '雙溪區', 'seq' => 9, 'used' => 1],
            ['postalcode' => '228', 'city_id' => '3', 'name' => '貢寮區', 'seq' => 10, 'used' => 1],
            ['postalcode' => '231', 'city_id' => '3', 'name' => '新店區', 'seq' => 11, 'used' => 1],
            ['postalcode' => '232', 'city_id' => '3', 'name' => '坪林區', 'seq' => 12, 'used' => 1],
            ['postalcode' => '233', 'city_id' => '3', 'name' => '烏來區', 'seq' => 13, 'used' => 1],
            ['postalcode' => '234', 'city_id' => '3', 'name' => '永和區', 'seq' => 14, 'used' => 1],
            ['postalcode' => '235', 'city_id' => '3', 'name' => '中和區', 'seq' => 15, 'used' => 1],
            ['postalcode' => '236', 'city_id' => '3', 'name' => '土城區', 'seq' => 16, 'used' => 1],
            ['postalcode' => '237', 'city_id' => '3', 'name' => '三峽區', 'seq' => 17, 'used' => 1],
            ['postalcode' => '238', 'city_id' => '3', 'name' => '樹林區', 'seq' => 18, 'used' => 1],
            ['postalcode' => '239', 'city_id' => '3', 'name' => '鶯歌區', 'seq' => 19, 'used' => 1],
            ['postalcode' => '241', 'city_id' => '3', 'name' => '三重區', 'seq' => 20, 'used' => 1],
            ['postalcode' => '242', 'city_id' => '3', 'name' => '新莊區', 'seq' => 21, 'used' => 1],
            ['postalcode' => '243', 'city_id' => '3', 'name' => '泰山區', 'seq' => 22, 'used' => 1],
            ['postalcode' => '244', 'city_id' => '3', 'name' => '林口區', 'seq' => 23, 'used' => 1],
            ['postalcode' => '247', 'city_id' => '3', 'name' => '蘆洲區', 'seq' => 24, 'used' => 1],
            ['postalcode' => '248', 'city_id' => '3', 'name' => '五股區', 'seq' => 25, 'used' => 1],
            ['postalcode' => '249', 'city_id' => '3', 'name' => '八里區', 'seq' => 26, 'used' => 1],
            ['postalcode' => '251', 'city_id' => '3', 'name' => '淡水區', 'seq' => 27, 'used' => 1],
            ['postalcode' => '252', 'city_id' => '3', 'name' => '三芝區', 'seq' => 28, 'used' => 1],
            ['postalcode' => '253', 'city_id' => '3', 'name' => '石門區', 'seq' => 29, 'used' => 1],
            //桃園市
            ['postalcode' => '320', 'city_id' => '4', 'name' => '中壢區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '324', 'city_id' => '4', 'name' => '平鎮區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '325', 'city_id' => '4', 'name' => '龍潭區', 'seq' => 3, 'used' => 1],
            ['postalcode' => '326', 'city_id' => '4', 'name' => '楊梅區', 'seq' => 4, 'used' => 1],
            ['postalcode' => '327', 'city_id' => '4', 'name' => '新屋區', 'seq' => 5, 'used' => 1],
            ['postalcode' => '328', 'city_id' => '4', 'name' => '觀音區', 'seq' => 6, 'used' => 1],
            ['postalcode' => '330', 'city_id' => '4', 'name' => '桃園區', 'seq' => 7, 'used' => 1],
            ['postalcode' => '333', 'city_id' => '4', 'name' => '龜山區', 'seq' => 8, 'used' => 1],
            ['postalcode' => '334', 'city_id' => '4', 'name' => '八德區', 'seq' => 9, 'used' => 1],
            ['postalcode' => '335', 'city_id' => '4', 'name' => '大溪區', 'seq' => 10, 'used' => 1],
            ['postalcode' => '336', 'city_id' => '4', 'name' => '復興區', 'seq' => 11, 'used' => 1],
            ['postalcode' => '337', 'city_id' => '4', 'name' => '大園區', 'seq' => 12, 'used' => 1],
            ['postalcode' => '338', 'city_id' => '4', 'name' => '蘆竹區', 'seq' => 13, 'used' => 1],
            //新竹市
            ['postalcode' => '300', 'city_id' => '5', 'name' => '東區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '300', 'city_id' => '5', 'name' => '北區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '300', 'city_id' => '5', 'name' => '香山區', 'seq' => 3, 'used' => 1],
            //新竹縣
            ['postalcode' => '302', 'city_id' => '6', 'name' => '竹北市', 'seq' => 1, 'used' => 1],
            ['postalcode' => '303', 'city_id' => '6', 'name' => '湖口鄉', 'seq' => 2, 'used' => 1],
            ['postalcode' => '304', 'city_id' => '6', 'name' => '新豐鄉', 'seq' => 3, 'used' => 1],
            ['postalcode' => '305', 'city_id' => '6', 'name' => '新埔鎮', 'seq' => 4, 'used' => 1],
            ['postalcode' => '306', 'city_id' => '6', 'name' => '關西鎮', 'seq' => 5, 'used' => 1],
            ['postalcode' => '307', 'city_id' => '6', 'name' => '芎林鄉', 'seq' => 6, 'used' => 1],
            ['postalcode' => '308', 'city_id' => '6', 'name' => '寶山鄉', 'seq' => 7, 'used' => 1],
            ['postalcode' => '310', 'city_id' => '6', 'name' => '竹東鎮', 'seq' => 8, 'used' => 1],
            ['postalcode' => '311', 'city_id' => '6', 'name' => '五峰鄉', 'seq' => 9, 'used' => 1],
            ['postalcode' => '312', 'city_id' => '6', 'name' => '橫山鄉', 'seq' => 10, 'used' => 1],
            ['postalcode' => '313', 'city_id' => '6', 'name' => '尖石鄉', 'seq' => 11, 'used' => 1],
            ['postalcode' => '314', 'city_id' => '6', 'name' => '北埔鄉', 'seq' => 12, 'used' => 1],
            ['postalcode' => '315', 'city_id' => '6', 'name' => '峨眉鄉', 'seq' => 13, 'used' => 1],
            //苗栗縣
            ['postalcode' => '350', 'city_id' => '7', 'name' => '竹南鎮', 'seq' => 1, 'used' => 1],
            ['postalcode' => '351', 'city_id' => '7', 'name' => '頭份市', 'seq' => 2, 'used' => 1],
            ['postalcode' => '352', 'city_id' => '7', 'name' => '三灣鄉', 'seq' => 3, 'used' => 1],
            ['postalcode' => '353', 'city_id' => '7', 'name' => '南庄鄉', 'seq' => 4, 'used' => 1],
            ['postalcode' => '354', 'city_id' => '7', 'name' => '獅潭鄉', 'seq' => 5, 'used' => 1],
            ['postalcode' => '356', 'city_id' => '7', 'name' => '後龍鎮', 'seq' => 6, 'used' => 1],
            ['postalcode' => '357', 'city_id' => '7', 'name' => '通霄鎮', 'seq' => 7, 'used' => 1],
            ['postalcode' => '358', 'city_id' => '7', 'name' => '苑裡鎮', 'seq' => 8, 'used' => 1],
            ['postalcode' => '360', 'city_id' => '7', 'name' => '苗栗市', 'seq' => 9, 'used' => 1],
            ['postalcode' => '361', 'city_id' => '7', 'name' => '造橋鄉', 'seq' => 10, 'used' => 1],
            ['postalcode' => '362', 'city_id' => '7', 'name' => '頭屋鄉', 'seq' => 11, 'used' => 1],
            ['postalcode' => '363', 'city_id' => '7', 'name' => '公館鄉', 'seq' => 12, 'used' => 1],
            ['postalcode' => '364', 'city_id' => '7', 'name' => '大湖鄉', 'seq' => 13, 'used' => 1],
            ['postalcode' => '365', 'city_id' => '7', 'name' => '泰安鄉', 'seq' => 14, 'used' => 1],
            ['postalcode' => '366', 'city_id' => '7', 'name' => '銅鑼鄉', 'seq' => 15, 'used' => 1],
            ['postalcode' => '367', 'city_id' => '7', 'name' => '三義鄉', 'seq' => 16, 'used' => 1],
            ['postalcode' => '368', 'city_id' => '7', 'name' => '西湖鄉', 'seq' => 17, 'used' => 1],
            ['postalcode' => '369', 'city_id' => '7', 'name' => '卓蘭鎮', 'seq' => 18, 'used' => 1],
            //台中市
            ['postalcode' => '400', 'city_id' => '8', 'name' => '中區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '401', 'city_id' => '8', 'name' => '東區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '402', 'city_id' => '8', 'name' => '南區', 'seq' => 3, 'used' => 1],
            ['postalcode' => '403', 'city_id' => '8', 'name' => '西區', 'seq' => 4, 'used' => 1],
            ['postalcode' => '404', 'city_id' => '8', 'name' => '北區', 'seq' => 5, 'used' => 1],
            ['postalcode' => '406', 'city_id' => '8', 'name' => '北屯區', 'seq' => 6, 'used' => 1],
            ['postalcode' => '407', 'city_id' => '8', 'name' => '西屯區', 'seq' => 7, 'used' => 1],
            ['postalcode' => '408', 'city_id' => '8', 'name' => '南屯區', 'seq' => 8, 'used' => 1],
            ['postalcode' => '411', 'city_id' => '8', 'name' => '太平區', 'seq' => 9, 'used' => 1],
            ['postalcode' => '412', 'city_id' => '8', 'name' => '大里區', 'seq' => 10, 'used' => 1],
            ['postalcode' => '413', 'city_id' => '8', 'name' => '霧峰區', 'seq' => 11, 'used' => 1],
            ['postalcode' => '414', 'city_id' => '8', 'name' => '烏日區', 'seq' => 12, 'used' => 1],
            ['postalcode' => '420', 'city_id' => '8', 'name' => '豐原區', 'seq' => 13, 'used' => 1],
            ['postalcode' => '421', 'city_id' => '8', 'name' => '后里區', 'seq' => 14, 'used' => 1],
            ['postalcode' => '422', 'city_id' => '8', 'name' => '石岡區', 'seq' => 15, 'used' => 1],
            ['postalcode' => '423', 'city_id' => '8', 'name' => '東勢區', 'seq' => 16, 'used' => 1],
            ['postalcode' => '424', 'city_id' => '8', 'name' => '和平區', 'seq' => 17, 'used' => 1],
            ['postalcode' => '426', 'city_id' => '8', 'name' => '新社區', 'seq' => 18, 'used' => 1],
            ['postalcode' => '427', 'city_id' => '8', 'name' => '潭子區', 'seq' => 19, 'used' => 1],
            ['postalcode' => '428', 'city_id' => '8', 'name' => '大雅區', 'seq' => 20, 'used' => 1],
            ['postalcode' => '429', 'city_id' => '8', 'name' => '神岡區', 'seq' => 21, 'used' => 1],
            ['postalcode' => '432', 'city_id' => '8', 'name' => '大肚區', 'seq' => 22, 'used' => 1],
            ['postalcode' => '433', 'city_id' => '8', 'name' => '沙鹿區', 'seq' => 23, 'used' => 1],
            ['postalcode' => '434', 'city_id' => '8', 'name' => '龍井區', 'seq' => 24, 'used' => 1],
            ['postalcode' => '435', 'city_id' => '8', 'name' => '梧棲區', 'seq' => 25, 'used' => 1],
            ['postalcode' => '436', 'city_id' => '8', 'name' => '清水區', 'seq' => 26, 'used' => 1],
            ['postalcode' => '437', 'city_id' => '8', 'name' => '大甲區', 'seq' => 27, 'used' => 1],
            ['postalcode' => '438', 'city_id' => '8', 'name' => '外埔區', 'seq' => 28, 'used' => 1],
            ['postalcode' => '439', 'city_id' => '8', 'name' => '大安區', 'seq' => 29, 'used' => 1],
            //彰化縣
            ['postalcode' => '500', 'city_id' => '9', 'name' => '彰化市', 'seq' => 1, 'used' => 1],
            ['postalcode' => '502', 'city_id' => '9', 'name' => '芬園鄉', 'seq' => 2, 'used' => 1],
            ['postalcode' => '503', 'city_id' => '9', 'name' => '花壇鄉', 'seq' => 3, 'used' => 1],
            ['postalcode' => '504', 'city_id' => '9', 'name' => '秀水鄉', 'seq' => 4, 'used' => 1],
            ['postalcode' => '505', 'city_id' => '9', 'name' => '鹿港鎮', 'seq' => 5, 'used' => 1],
            ['postalcode' => '506', 'city_id' => '9', 'name' => '福興鄉', 'seq' => 6, 'used' => 1],
            ['postalcode' => '507', 'city_id' => '9', 'name' => '線西鄉', 'seq' => 7, 'used' => 1],
            ['postalcode' => '508', 'city_id' => '9', 'name' => '和美鎮', 'seq' => 8, 'used' => 1],
            ['postalcode' => '509', 'city_id' => '9', 'name' => '伸港鄉', 'seq' => 9, 'used' => 1],
            ['postalcode' => '510', 'city_id' => '9', 'name' => '員林鎮', 'seq' => 10, 'used' => 1],
            ['postalcode' => '511', 'city_id' => '9', 'name' => '社頭鄉', 'seq' => 11, 'used' => 1],
            ['postalcode' => '512', 'city_id' => '9', 'name' => '永靖鄉', 'seq' => 12, 'used' => 1],
            ['postalcode' => '513', 'city_id' => '9', 'name' => '埔心鄉', 'seq' => 13, 'used' => 1],
            ['postalcode' => '514', 'city_id' => '9', 'name' => '溪湖鎮', 'seq' => 14, 'used' => 1],
            ['postalcode' => '515', 'city_id' => '9', 'name' => '大村鄉', 'seq' => 15, 'used' => 1],
            ['postalcode' => '516', 'city_id' => '9', 'name' => '埔鹽鄉', 'seq' => 16, 'used' => 1],
            ['postalcode' => '520', 'city_id' => '9', 'name' => '田中鎮', 'seq' => 17, 'used' => 1],
            ['postalcode' => '521', 'city_id' => '9', 'name' => '北斗鎮', 'seq' => 18, 'used' => 1],
            ['postalcode' => '522', 'city_id' => '9', 'name' => '田尾鄉', 'seq' => 19, 'used' => 1],
            ['postalcode' => '523', 'city_id' => '9', 'name' => '埤頭鄉', 'seq' => 20, 'used' => 1],
            ['postalcode' => '524', 'city_id' => '9', 'name' => '溪州鄉', 'seq' => 21, 'used' => 1],
            ['postalcode' => '525', 'city_id' => '9', 'name' => '竹塘鄉', 'seq' => 22, 'used' => 1],
            ['postalcode' => '526', 'city_id' => '9', 'name' => '二林鎮', 'seq' => 23, 'used' => 1],
            ['postalcode' => '527', 'city_id' => '9', 'name' => '大城鄉', 'seq' => 24, 'used' => 1],
            ['postalcode' => '528', 'city_id' => '9', 'name' => '芳苑鄉', 'seq' => 25, 'used' => 1],
            ['postalcode' => '530', 'city_id' => '9', 'name' => '二水鄉', 'seq' => 26, 'used' => 1],
            //南投縣
            ['postalcode' => '540', 'city_id' => '10', 'name' => '南投市', 'seq' => 1, 'used' => 1],
            ['postalcode' => '541', 'city_id' => '10', 'name' => '中寮鄉', 'seq' => 2, 'used' => 1],
            ['postalcode' => '542', 'city_id' => '10', 'name' => '草屯鎮', 'seq' => 3, 'used' => 1],
            ['postalcode' => '544', 'city_id' => '10', 'name' => '國姓鄉', 'seq' => 4, 'used' => 1],
            ['postalcode' => '545', 'city_id' => '10', 'name' => '埔里鎮', 'seq' => 5, 'used' => 1],
            ['postalcode' => '546', 'city_id' => '10', 'name' => '仁愛鄉', 'seq' => 6, 'used' => 1],
            ['postalcode' => '551', 'city_id' => '10', 'name' => '名間鄉', 'seq' => 7, 'used' => 1],
            ['postalcode' => '552', 'city_id' => '10', 'name' => '集集鎮', 'seq' => 8, 'used' => 1],
            ['postalcode' => '553', 'city_id' => '10', 'name' => '水里鄉', 'seq' => 9, 'used' => 1],
            ['postalcode' => '555', 'city_id' => '10', 'name' => '魚池鄉', 'seq' => 10, 'used' => 1],
            ['postalcode' => '556', 'city_id' => '10', 'name' => '信義鄉', 'seq' => 11, 'used' => 1],
            ['postalcode' => '557', 'city_id' => '10', 'name' => '竹山鎮', 'seq' => 12, 'used' => 1],
            ['postalcode' => '558', 'city_id' => '10', 'name' => '鹿谷鄉', 'seq' => 13, 'used' => 1],
            //雲林縣
            ['postalcode' => '630', 'city_id' => '11', 'name' => '斗南鎮', 'seq' => 1, 'used' => 1],
            ['postalcode' => '631', 'city_id' => '11', 'name' => '大埤鄉', 'seq' => 2, 'used' => 1],
            ['postalcode' => '632', 'city_id' => '11', 'name' => '虎尾鎮', 'seq' => 3, 'used' => 1],
            ['postalcode' => '633', 'city_id' => '11', 'name' => '土庫鎮', 'seq' => 4, 'used' => 1],
            ['postalcode' => '634', 'city_id' => '11', 'name' => '褒忠鄉', 'seq' => 5, 'used' => 1],
            ['postalcode' => '635', 'city_id' => '11', 'name' => '東勢鄉', 'seq' => 6, 'used' => 1],
            ['postalcode' => '636', 'city_id' => '11', 'name' => '臺西鄉', 'seq' => 7, 'used' => 1],
            ['postalcode' => '637', 'city_id' => '11', 'name' => '崙背鄉', 'seq' => 8, 'used' => 1],
            ['postalcode' => '638', 'city_id' => '11', 'name' => '麥寮鄉', 'seq' => 9, 'used' => 1],
            ['postalcode' => '640', 'city_id' => '11', 'name' => '斗六市', 'seq' => 10, 'used' => 1],
            ['postalcode' => '643', 'city_id' => '11', 'name' => '林內鄉', 'seq' => 11, 'used' => 1],
            ['postalcode' => '646', 'city_id' => '11', 'name' => '古坑鄉', 'seq' => 12, 'used' => 1],
            ['postalcode' => '647', 'city_id' => '11', 'name' => '莿桐鄉', 'seq' => 13, 'used' => 1],
            ['postalcode' => '648', 'city_id' => '11', 'name' => '西螺鎮', 'seq' => 14, 'used' => 1],
            ['postalcode' => '649', 'city_id' => '11', 'name' => '二崙鄉', 'seq' => 15, 'used' => 1],
            ['postalcode' => '651', 'city_id' => '11', 'name' => '北港鎮', 'seq' => 16, 'used' => 1],
            ['postalcode' => '652', 'city_id' => '11', 'name' => '水林鄉', 'seq' => 17, 'used' => 1],
            ['postalcode' => '653', 'city_id' => '11', 'name' => '口湖鄉', 'seq' => 18, 'used' => 1],
            ['postalcode' => '654', 'city_id' => '11', 'name' => '四湖鄉', 'seq' => 19, 'used' => 1],
            ['postalcode' => '655', 'city_id' => '11', 'name' => '元長鄉', 'seq' => 20, 'used' => 1],
            //嘉義市
            ['postalcode' => '600', 'city_id' => '12', 'name' => '東區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '600', 'city_id' => '12', 'name' => '西區', 'seq' => 2, 'used' => 1],
            //嘉義縣
            ['postalcode' => '602', 'city_id' => '13', 'name' => '番路鄉', 'seq' => 1, 'used' => 1],
            ['postalcode' => '603', 'city_id' => '13', 'name' => '梅山鄉', 'seq' => 2, 'used' => 1],
            ['postalcode' => '604', 'city_id' => '13', 'name' => '竹崎鄉', 'seq' => 3, 'used' => 1],
            ['postalcode' => '605', 'city_id' => '13', 'name' => '阿里山', 'seq' => 4, 'used' => 1],
            ['postalcode' => '606', 'city_id' => '13', 'name' => '中埔鄉', 'seq' => 5, 'used' => 1],
            ['postalcode' => '607', 'city_id' => '13', 'name' => '大埔鄉', 'seq' => 6, 'used' => 1],
            ['postalcode' => '608', 'city_id' => '13', 'name' => '水上鄉', 'seq' => 7, 'used' => 1],
            ['postalcode' => '611', 'city_id' => '13', 'name' => '鹿草鄉', 'seq' => 8, 'used' => 1],
            ['postalcode' => '612', 'city_id' => '13', 'name' => '太保市', 'seq' => 9, 'used' => 1],
            ['postalcode' => '613', 'city_id' => '13', 'name' => '朴子市', 'seq' => 10, 'used' => 1],
            ['postalcode' => '614', 'city_id' => '13', 'name' => '東石鄉', 'seq' => 11, 'used' => 1],
            ['postalcode' => '615', 'city_id' => '13', 'name' => '六腳鄉', 'seq' => 12, 'used' => 1],
            ['postalcode' => '616', 'city_id' => '13', 'name' => '新港鄉', 'seq' => 13, 'used' => 1],
            ['postalcode' => '621', 'city_id' => '13', 'name' => '民雄鄉', 'seq' => 14, 'used' => 1],
            ['postalcode' => '622', 'city_id' => '13', 'name' => '大林鎮', 'seq' => 15, 'used' => 1],
            ['postalcode' => '623', 'city_id' => '13', 'name' => '溪口鄉', 'seq' => 16, 'used' => 1],
            ['postalcode' => '624', 'city_id' => '13', 'name' => '義竹鄉', 'seq' => 17, 'used' => 1],
            ['postalcode' => '625', 'city_id' => '13', 'name' => '布袋鎮', 'seq' => 18, 'used' => 1],
            //台南市
            ['postalcode' => '700', 'city_id' => '14', 'name' => '中區', 'seq' => 1, 'used' => 1],
            ['postalcode' => '701', 'city_id' => '14', 'name' => '東區', 'seq' => 2, 'used' => 1],
            ['postalcode' => '702', 'city_id' => '14', 'name' => '南區', 'seq' => 3, 'used' => 1],
            ['postalcode' => '704', 'city_id' => '14', 'name' => '北區', 'seq' => 4, 'used' => 1],
            ['postalcode' => '708', 'city_id' => '14', 'name' => '安平區', 'seq' => 5, 'used' => 1],
            ['postalcode' => '709', 'city_id' => '14', 'name' => '安南區', 'seq' => 6, 'used' => 1],
            ['postalcode' => '710', 'city_id' => '14', 'name' => '永康區', 'seq' => 7, 'used' => 1],
            ['postalcode' => '711', 'city_id' => '14', 'name' => '歸仁區', 'seq' => 8, 'used' => 1],
            ['postalcode' => '712', 'city_id' => '14', 'name' => '新化區', 'seq' => 9, 'used' => 1],
            ['postalcode' => '713', 'city_id' => '14', 'name' => '左鎮區', 'seq' => 10, 'used' => 1],
            ['postalcode' => '714', 'city_id' => '14', 'name' => '玉井區', 'seq' => 11, 'used' => 1],
            ['postalcode' => '715', 'city_id' => '14', 'name' => '楠西區', 'seq' => 12, 'used' => 1],
            ['postalcode' => '716', 'city_id' => '14', 'name' => '南化區', 'seq' => 13, 'used' => 1],
            ['postalcode' => '717', 'city_id' => '14', 'name' => '仁德區', 'seq' => 14, 'used' => 1],
            ['postalcode' => '718', 'city_id' => '14', 'name' => '關廟區', 'seq' => 15, 'used' => 1],
            ['postalcode' => '719', 'city_id' => '14', 'name' => '龍崎區', 'seq' => 16, 'used' => 1],
            ['postalcode' => '720', 'city_id' => '14', 'name' => '官田區', 'seq' => 17, 'used' => 1],
            ['postalcode' => '721', 'city_id' => '14', 'name' => '麻豆區', 'seq' => 18, 'used' => 1],
            ['postalcode' => '722', 'city_id' => '14', 'name' => '佳里區', 'seq' => 19, 'used' => 1],
            ['postalcode' => '723', 'city_id' => '14', 'name' => '西港區', 'seq' => 20, 'used' => 1],
            ['postalcode' => '724', 'city_id' => '14', 'name' => '七股區', 'seq' => 21, 'used' => 1],
            ['postalcode' => '725', 'city_id' => '14', 'name' => '將軍區', 'seq' => 22, 'used' => 1],
            ['postalcode' => '726', 'city_id' => '14', 'name' => '學甲區', 'seq' => 23, 'used' => 1],
            ['postalcode' => '727', 'city_id' => '14', 'name' => '北門區', 'seq' => 24, 'used' => 1],
            ['postalcode' => '730', 'city_id' => '14', 'name' => '新營區', 'seq' => 25, 'used' => 1],
            ['postalcode' => '731', 'city_id' => '14', 'name' => '後壁區', 'seq' => 26, 'used' => 1],
            ['postalcode' => '732', 'city_id' => '14', 'name' => '白河區', 'seq' => 27, 'used' => 1],
            ['postalcode' => '733', 'city_id' => '14', 'name' => '東山區', 'seq' => 28, 'used' => 1],
            ['postalcode' => '734', 'city_id' => '14', 'name' => '六甲區', 'seq' => 29, 'used' => 1],
            ['postalcode' => '735', 'city_id' => '14', 'name' => '下營區', 'seq' => 30, 'used' => 1],
            ['postalcode' => '736', 'city_id' => '14', 'name' => '柳營區', 'seq' => 31, 'used' => 1],
            ['postalcode' => '737', 'city_id' => '14', 'name' => '鹽水區', 'seq' => 32, 'used' => 1],
            ['postalcode' => '741', 'city_id' => '14', 'name' => '善化區', 'seq' => 33, 'used' => 1],
            ['postalcode' => '742', 'city_id' => '14', 'name' => '大內區', 'seq' => 34, 'used' => 1],
            ['postalcode' => '743', 'city_id' => '14', 'name' => '山上區', 'seq' => 35, 'used' => 1],
            ['postalcode' => '744', 'city_id' => '14', 'name' => '新市區', 'seq' => 36, 'used' => 1],
            ['postalcode' => '745', 'city_id' => '14', 'name' => '安定區', 'seq' => 37, 'used' => 1],
        ];

        DB::table('cityareas')->insert($cityarea);

        
    }
}
